### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by FreekingDean** [maurycyp/vincenty#1]
Hi there, I am not sure if this is abandoned or not, but it seems that the file permissions in the PyPI source tarball are set to disallow Reads from the Group and Everyone groups. Is this for any specific reason?

I am attempting to make a package for arch to allow the package manager to manage this python lib.

Thanks!

**Comment by maurycyp** [comment]
@FreekingDean Hi, it's definitely not abandoned.  The permissions issue sounds like a fluke.  I'll look into it and post 0.1.4 if necessary.

**Comment by maurycyp** [comment]
P.S. Thanks for creating the issue.

**Comment by FreekingDean** [comment]
No problem! Thanks for looking into it. I'll let you know when the package
for Arch Linux is up!

**Comment by FreekingDean** [comment]
The package is up https://aur.archlinux.org/packages/python-vincenty/

**Comment by maurycyp** [comment]
:+1:

**Comment by maurycyp** [comment]
Hi Dean, I've released 0.1.4, which should fix the permissions. Let me know if everything looks good on your end.

**Comment by maurycyp** [comment]
@FreekingDean If everything looks good on your end, then I will close out the issue.
